# Generated by Django 2.0.5 on 2018-06-22 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Hero name')),
                ('occurence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Map name')),
            ],
        ),
        migrations.CreateModel(
            name='RankTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rank', models.IntegerField()),
                ('variation', models.IntegerField()),
                ('heros', models.ManyToManyField(to='RankTrackerImpl.Hero')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RankTrackerImpl.Map')),
                ('tab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RankTrackerImpl.Accounts')),
            ],
        ),
    ]
