# Generated by Django 2.0.5 on 2018-06-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankTrackerImpl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='occurence',
            field=models.IntegerField(default=0),
        ),
    ]
