# Generated by Django 2.0.5 on 2018-06-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankTrackerImpl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.DeleteModel(
            name='TabAccount',
        ),
    ]
