# Generated by Django 2.0.5 on 2018-06-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RankTrackerImpl', '0002_auto_20180609_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='account_name',
            new_name='name',
        ),
    ]
