# Generated by Django 2.0.5 on 2018-06-09 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RankTrackerImpl', '0003_auto_20180609_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranktable',
            name='tab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RankTrackerImpl.Accounts'),
        ),
    ]
