# Generated by Django 2.0.5 on 2018-06-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RankTrackerImpl', '0003_auto_20180622_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ('-occurence', 'id')},
        ),
    ]
